name: platform
services:
  postgres:
    image: postgres@sha256:20edbde7749f822887a1a022ad526fde0a47d6b2be9a8364433605cf65099416
    container_name: platform-postgres
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      AUTHENTIK_DB_PASSWORD: ${AUTHENTIK_DB_PASSWORD}
      N8N_DB_PASSWORD: ${N8N_DB_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./initdb/postgres:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - stack-net

  mariadb:
    image: mariadb@sha256:8164f184d16c30e2f159e30518113667b796306dff0fe558876ab1ff521a682f
    container_name: platform-mariadb
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      TZ: ${TZ}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./initdb/mariadb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - stack-net

networks:
  stack-net:
    external: true
